miasta = ['Częstochowa', 'Świętochłowice', 'Chorzów', 'Katowice', 'Kijów', 'Charków']
print(miasta)
print(sorted(miasta))
print(miasta)
print(sorted(miasta,reverse=True))
print(miasta)
miasta.reverse()
print(miasta)
miasta.reverse()
print(miasta)
miasta.sort()
print(miasta)
miasta.sort(reverse=True)
print(miasta)

