swiat = ['Kanada', 'Ukraina', 'Czarnogóra', 'Dania', 'Szwajcaria']
print(swiat)
print(sorted(swiat))
print(swiat)
print(sorted(swiat,reverse=True))
print(swiat)
swiat.reverse()
print(swiat)
swiat.reverse()
print(swiat)
swiat.sort()
print(swiat)
swiat.sort(reverse=True)
print(swiat)
